### PR TITLE
Test and fix cases with nested contexts

### LINKED ISSUE #8: False positive for contexts stored in structs
Love the concept, but I got stung by a false positive involving a struct that contains a context. (Yeah, yeah, I know that's not preferred.) I can repro by adding either of the following to the test:

```go
    var c = struct { Ctx context.Context }{ctx}
    for i := 0; i < 10; i++ {
        c := c
        c.Ctx = context.WithValue(c.Ctx, "key", i) // here
        c.Ctx = context.WithValue(c.Ctx, "other", "val")
    }
```

```go
    for i := 0; i < 10; i++ {
        var c = struct { Ctx context.Context }{ctx}
        c.Ctx = context.WithValue(c.Ctx, "key", i) // here
        c.Ctx = context.WithValue(c.Ctx, "other", "val")
    }
```

My actual case is more like the first, but the second is more clearly a false positive. It looks like this comes down to not recognizing this as a case that breaks the chain, continuing due to t.String() != "context.Context" instead of breaking due to assignStmt.Tok == token.DEFINE. But solving this seems like a bear, especially as a syntactically very similar case should likely still be reported:

```go
    var c = &struct { Ctx context.Context }{ctx}
    for i := 0; i < 10; i++ {
        c := c
        c.Ctx = context.WithValue(c.Ctx, "key", i) // want "nested context in loop"
        c.Ctx = context.WithValue(c.Ctx, "other", "val")
    }
```

I can't look today but let me know if you'd want me to attempt a solution. My guess is that pass.TypesInfo's Defs and Uses could disambiguate these, at least if filtered by appropriate levels of indirection in their containers.

### PR DESCRIPTION
**Pull request by MichaelUrman**
As long as the context is rooted in a non-pointer value that has a new copy in the loop, it is as safe to copy that value as it is to copy the context. So only report such cases when they are indirected and thus shared.

Fixes #8

### CODE REVIEW

File: pkg/analyzer/analyzer.go [hunk 1]
```diff
@@ -54,6 +55,14 @@ func run(pass *analysis.Pass) (interface{}, error) {
 				break
 			}
 
+			if lhs := getRootIdent(pass, assignStmt.Lhs[0]); lhs != nil {
+				if obj := pass.TypesInfo.ObjectOf(lhs); obj != nil {
+					if obj.Pos() >= body.Pos() && obj.Pos() < body.End() {
+						continue
+					}
+				}
+			}
```
Comment (Crocmagnon) [inline pkg/analyzer/analyzer.go:64]: Could you add a comment explaining the reason behind this block?

Otherwise LGTM :shipit: 🚀

Comment (MichaelUrman) [reply pkg/analyzer/analyzer.go:65]: Done. How's that explanation?

**Review by Crocmagnon — APPROVED** [review]
